

spring:
  application:
    name: Badge-and-Membership-System

#  spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
#  spring.datasource.username=${MYSQLUSER}
#  spring.datasource.password=${MYSQLPASSWORD}

  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximumPoolSize: 10


  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect
        show-sql: true
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

## jwt configs ##
jwt:
  secret: secret
  expiration: 86400000

## maintaining logs ##

#logging:
#  file:
#    name: application.log

# Email settings
  spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: miu.alumni.management.portal@gmail.com
      password: fvmerzybvaodqklj
      properties:
        mail:
          smtp:
            auth: false
            starttls:
              enable: true
server:
  port: 8081